AWSTemplateFormatVersion: 2010-09-09
Description: Root Stack Template

Parameters:
  myKeyName:
    Type: AWS::EC2::KeyPair::KeyName

  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR Range
  
  Subnet01Block:
    Type: String
    Default: 10.0.1.0/24
    Description: Cidr Block for Subnet01 within VPC

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nestedstackbuck.s3-us-west-1.amazonaws.com/17.aws_ec2_nestedStack.yml
      Parameters: 
        VpcBlock: !Ref VpcBlock
        Subnet01Block: !Ref Subnet01Block
  
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nestedstackbuck.s3-us-west-1.amazonaws.com/19.aws_ec2_NestedStack_SecurityGroup.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04bc3da8f14823e88
      InstanceType: t2.micro
      KeyName: !Ref myKeyName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !GetAtt VPCStack.Outputs.Subnet01Id
          GroupSet:
            - !GetAtt SecurityGroupStack.Outputs.DevSGroupId
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y erase java-1.7.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk-devel
          sudo yum -y install tomcat8
          sudo service tomcat8 start
          sudo mkdir /usr/share/tomcat8/webapps/ROOT
          sudo touch /usr/share/tomcat8/webapps/ROOT/index.html
          sudo echo "Cloud formation Tomcat8 sample" > /usr/share/tomcat8/webapps/ROOT/index.html

Outputs:
  AppURL:
    Description: my application url to access
    Value: !Sub 'http://${MyVMInstance.PublicDnsName}:8080/index.html'
      


