AWSTemplateFormatVersion: 2010-09-09
Description: Sample Cloud Formation Template
Resources:
  MyEc2Instance:
    Description: My EC2 instance
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-062f7200baf2fa504
      KeyName: LearningKey
      SecurityGroups: 
        - default
        - !Ref MySSHSecurityGroup
  MySSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: My own Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0      
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0      
  MyElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref MyEc2Instance